[project]
authors = ["Jacob Williams <jacobwilliams@users.noreply.github.com>"]
channels = ["conda-forge", "panda3d-forge"]
name = "env"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
panda3d = ">=1.10.15,<2"
qtpy = ">=2.4.3,<3"
python = "3.10.*"
pyside6 = ">=6.8.3,<7"
psutil = ">=7.0.0,<8"
imageio = ">=2.37.0,<3"
ffmpeg = ">=7.1.1,<8"
imageio-ffmpeg = ">=0.6.0,<0.7"
scipy = ">=1.15.2,<2"
json5 = ">=0.12.0,<0.13"
pdoc = ">=14.4.0,<15"
